source/src/enet_encap/encap.c

Closes #19 - Limits mayDelayTime to 2000 milliseconds

---

source/src/enet_encap/cpf.c

EtherNet/IP specification doesn't demand it, but there are EIP
devices which depend on CPF items to appear in the order of their
ID number. We encountered that problem with a FANUC controller.

Order CPF sockaddr info items by ID number on the wire

---

source/src/cip/ciptcpipinterface.c
source/src/cip/ciptcpipinterface.h
source/src/ports/generic_networkhandler.c
source/src/ports/generic_networkhandler.h

- Implementation and insertion of attribute 13 (Encapsulation Inactivity Timeout)
- Implementation of SetAttributeSingleTcpIpInterface for attribute 3 and 13
- Modification of GetAttributeAllTcpIpInterface (Unimplemented attributes in the response use the default attribute values)
- Implementation of Encapsulation Inactivity Timout Timer

Updates TCP/IP object to revision 4

---

source/src/cip/cipconnectionmanager.c
source/src/cip/cipioconnection.c

Reamining path sould be managed in 16-bit words

Bug Configuration data - ParseConnectionPath()

---

source/src/cip/cipconnectionmanager.c
source/src/cip/cipioconnection.c

OpenMulticastConnection() fucntion requieres to know address_info_item[i].type_id.
Type_id sould be assigned before using it in
OpenMulticastConnection().

Bug open multicast connection

---

source/src/cip/cipconnectionmanager.c
source/src/cip/cipioconnection.c
source/src/enet_encap/encap.c
source/src/opener_api.h
source/src/ports/POSIX/networkhandler.c
source/src/ports/generic_networkhandler.c
source/src/ports/generic_networkhandler.h
source/src/ports/socket_timer.c

Fixes #87, see issue comments, adds trace infos

---

.travis.yml
source/CMakeLists.txt
source/buildsupport/POSIX/OpENer_PLATFORM_INCLUDES.cmake
source/src/cip/cipcommon.c
source/src/cip/cipconnectionmanager.c
source/src/cip/cipconnectionmanager.h
source/src/cip/cipioconnection.c
source/src/cip/cipmessagerouter.c
source/src/ports/POSIX/CMakeLists.txt
source/src/ports/WIN32/networkhandler.c
source/src/ports/generic_networkhandler.c
source/tests/CMakeLists.txt
source/tests/OpENerTests.h
source/tests/cip/CMakeLists.txt
source/tests/cip/cipconnectionmanagertest.cpp

Updated pull request from #110

Reorde master

---

source/src/cip/appcontype.c
source/src/cip/cipconnectionmanager.c
source/src/cip/cipconnectionobject.c
source/src/cip/cipconnectionobject.h
source/src/cip/cipioconnection.c
source/src/ports/POSIX/networkhandler.c
source/src/utils/doublylinkedlist.c
source/tests/utils/doublylinkedlistTests.cpp

Closes #127 - fixes timeout behavior for IO connections

Closes #127 - fixes timeout behavior for IO connections

---

.travis.yml

Closes #129
Signed-off-by: CapXilinx <melik-merkumians@acin.tuwien.ac.at>

Updates travis.yml

---

source/src/cip/appcontype.c
source/src/cip/cipassembly.c
source/src/cip/cipclass3connection.c
source/src/cip/cipcommon.c
source/src/cip/cipcommon.h
source/src/cip/cipconnectionmanager.c
source/src/cip/cipconnectionmanager.h
source/src/cip/cipconnectionobject.c
source/src/cip/cipconnectionobject.h
source/src/cip/cipethernetlink.c
source/src/cip/cipethernetlink.h
source/src/cip/cipidentity.c
source/src/cip/cipioconnection.c
source/src/cip/cipmessagerouter.c
source/src/cip/cipmessagerouter.h
source/src/cip/cipqos.c
source/src/cip/ciptcpipinterface.c
source/src/cip/ciptypes.h
source/src/enet_encap/cpf.c
source/src/enet_encap/encap.c
source/src/enet_encap/encap.h
source/src/ports/POSIX/networkconfig.c
source/src/ports/POSIX/networkhandler.c
source/src/ports/POSIX/networkhandler.h
source/src/ports/generic_networkhandler.c

Fixes timout behavior also for Class3 connections

Closes #131 Issue 131

---

README.md
source/src/ports/WIN32/CMakeLists.txt
source/src/ports/WIN32/main.c
source/src/ports/WIN32/networkconfig.c
source/src/ports/WIN32/networkhandler.c
source/src/ports/WIN32/networkhandler.h

Adds the readout of the network configuration for Windows

Read Network

---

source/src/enet_encap/encap.c

- Modified DetermineDelayTime() formula to compute delay. The computed delay would be between 0 to default 90% maximum_delay_time sent by requester
- Modified HandleReceivedListIdentityCommandUdp() & ManageEncapsulationMessages to store and send delayed ListIdentity response message respectively

Fix for issue#180. Following are done as part of fix:

---

source/src/cip/cipmessagerouter.c

* Corrected memory free operation for multi instance classes.

Issue#185: Memory double-free in multi-instance classes

---

source/src/cip/ciptypes.h
source/src/ports/WIN32/networkconfig.c

Thanks for this great commit @jvalenzuela !

Jvalenzuela dns server

---

.travis.yml
travis_scripts/linuxAfterSuccessScript.sh
travis_scripts/linuxBeforeScript.sh
travis_scripts/linuxScript.sh
travis_scripts/windowsMinGWScript.sh
travis_scripts/windowsScript.sh

Adds builds for MSVC and MinGW to Travis CI

Travis multi os build

---

source/src/cip/cipassembly.c
source/src/cip/cipcommon.c
source/src/cip/cipcommon.h
source/src/cip/cipconnectionmanager.c
source/src/cip/cipepath.c
source/src/cip/cipepath.h
source/src/cip/cipethernetlink.c
source/src/cip/cipethernetlink.h
source/src/cip/cipidentity.c
source/src/cip/cipmessagerouter.c
source/src/cip/cipqos.c
source/src/cip/ciptcpipinterface.c
source/src/cip/ciptypes.h
source/src/enet_encap/cpf.c
source/src/enet_encap/cpf.h
source/src/enet_encap/encap.c
source/src/opener_api.h
source/src/ports/generic_networkhandler.c

Adds patches provided by @stm-at-esd

Closes #214

---

source/src/ports/MINGW/CMakeLists.txt
source/src/ports/WIN32/CMakeLists.txt

Closes #266 updates drop-in in MinGW and Windows

---

source/CMakeLists.txt
source/src/cip/cipcommon.c
source/src/enet_encap/endianconv.c
source/src/enet_encap/endianconv.h
source/src/typedefs.h
travis_scripts/linuxScript.sh
travis_scripts/windowsMinGWScript.sh
travis_scripts/windowsScript.sh

Closes #187 Remove 64bit switch

---

source/src/ports/nvdata/nvqos.c

Fix regarding fscanf data types

---

source/src/cip/cipcommon.c

Fixes loop counter incremeted in loop body

---

source/src/cip/cipclass3connection.c
source/src/cip/cipclass3connection.h
source/src/cip/cipioconnection.c
source/src/cip/cipioconnection.h

Fixes some CipError/EipStatus mixups

---

source/src/cip/cipethernetlink.c

SonarCloud issue

---

source/src/ports/POSIX/networkconfig.c

SonarCloud issue fix

---

source/src/ports/nvdata/conffile.c
source/src/ports/nvdata/conffile.h
source/src/ports/nvdata/nvdata.c
source/src/ports/nvdata/nvqos.c
source/src/ports/nvdata/nvtcpip.c

Tries to fix SonarClouds problems

---

travis_scripts/linuxScript.sh

Remove tests and ports from coverage

---

.travis.yml

Test suggestions

---

source/src/ports/nvdata/conffile.c
source/src/ports/nvdata/nvdata.c
source/src/ports/nvdata/nvqos.c
source/src/ports/nvdata/nvtcpip.c

Updates doxygen

---

source/src/cip/appcontype.c
source/src/cip/cipassembly.c

Adds const keywords

---

source/src/cip/cipioconnection.c

Signed-off-by: Vincent Prince <vincent.prince.fr@gmail.com>

Produced heartbeat shouldn't have run/idle header

---

source/src/enet_encap/endianconv.c
source/src/enet_encap/endianconv.h
source/tests/enet_encap/endianconvtest.cpp

Increases code coverage

---

source/src/cip/cipcommon.c
source/src/cip/cipconnectionmanager.c
source/src/cip/cipconnectionobject.c
source/src/cip/cipepath.c
source/src/cip/cipioconnection.c
source/src/enet_encap/cpf.c
source/src/enet_encap/encap.c
source/src/enet_encap/endianconv.c
source/src/enet_encap/endianconv.h
source/src/ports/generic_networkhandler.c

Fixes errors due to more typifed endian conversion API

Correct endian conv

---

source/src/enet_encap/cpf.c

Prevents wrong item count to write over boundaries

---

source/doc/opener.bib
source/opener.doxyfile.in

Created a doxygen bibliography to create citations to the CIP specs, rather than typing the entire document volume, edition, date, etc every time you want to reference something in the code documentation.

Doxygen bibliography

---

source/src/ports/generic_networkhandler.c
source/src/ports/generic_networkhandler.h

and the actual global var in the C file

Fixes #370 extern needs to be in header

---

source/CMakeLists.txt
source/buildsupport/OpENer_Tests.cmake
source/src/ports/MINGW/CMakeLists.txt
source/src/ports/MINGW/sample_application/opener_user_conf.h
source/src/ports/POSIX/CMakeLists.txt
source/src/ports/POSIX/sample_application/opener_user_conf.h
source/src/ports/WIN32/CMakeLists.txt
source/src/ports/WIN32/sample_application/opener_user_conf.h
source/tests/CMakeLists.txt
source/tests/OpENerTests.cpp
source/tests/callback_mock.cpp
source/tests/check_assert.h
source/tests/cip/CMakeLists.txt
source/tests/cip/cipstringtests.cpp
source/tests/test_assert.h

Various fixes and improvements to unit tests.

Unit test fixes

---

.gitignore
source/src/cip/cipcommon.c
source/src/cip/cipcommon.h

The class attribute #2 (max_instance)  was not updated in AddCipInstance function - fixed now

cipcommon max_instance BUGFIX

---

source/src/ports/WIN32/networkhandler.c

Resolves Visual Studio warning C4081.

Fix pragma warning

---

source/src/ports/generic_networkhandler.c

Please check this on mingw/cigwin; I don't have access to a 64-bit Windows machine to try these ports.

Select different pragma statements for GCC/MSVC.

---

source/src/ports/generic_networkhandler.c

Fix the issue 524: memory leak
