- source/src/cip/cipclass3connection.c
- source/src/cip/cipclass3connection.h
- source/src/cip/cipioconnection.c
- source/src/cip/cipioconnection.h
- source/src/opener_api.h
- source/src/ports/generic_networkhandler.h
Some of the cip functions where declared and/or implemented with return type int, while returning EipStatus. This was inconsistent with the rest.
generic_networkhandler.h had no include guard. Don't know if it's realy necessary, but it's probably better to have one.
> Unified return types to "EipStatus" and add include guard to generic_networkhandler.h

- source/src/enet_encap/encap.c
- source/src/typedefs.h
The assignment of int values to an enum-type, beyond the range of all members in that type may lead (and has for me) to undefined behaviour. From C Standard (C99):
> 6.7.2.2 Enumeration specifiers
> [...]
> Each enumerated type shall be compatible with char, a signed integer type, or an unsigned integer type. The choice of type is implementation-defined, but shall be capable of representing the values of all the members of the enumeration.
> Undefined behaviour due to assignment of int to enum-type

- source/src/ports/generic_networkhandler.c
g_encapsulation_inactivity_timeout is in units of seconds, but was being
used as milliseconds.
> Fix encapsulation inactivity socket timeout.

- source/src/ports/MINGW/main.c
- source/src/ports/MINGW/sample_application/opener_user_conf.h
Fix a few problems with MINGW. The compile failes with traces enabled. This may be a problem with POSIX/WIN builds also.  The ConfigureDomain call should have no parameters, and the typedefs.h must be included to avoid errors in other files.
> Fix mingw call to configureDomain and missing types

- source/src/cip/ciptypes.h
- source/src/ports/WIN32/networkconfig.c
The interface_configuration_ struct stores DNS addresses as CipUdint,
not strings, so network-to-presentation(Ntop) conversion is wrong. Also,
this fixes a problem with selecting an adapter with less than two DNS
servers configured, as the FirstDnsServerAddress linked list may be less
than two entries long.
> Fix DNS server address retrieval.

- source/src/cip/cipcommon.c
- source/src/cip/cipmessagerouter.c
As described in #250, memory management was missing several structures and due to the allocation of one lump of memory in some aspects limited.
These commits fix and updates the memory alloaction/deallocation of CIP Objects.
> Closes #250 updates memory management for CIP objects

- source/src/cip/cipidentity.h
- source/src/cip/cipqos.c
- source/src/cip/cipqos.h
- source/src/ports/nvdata/nvqos.c
`CipUsint explicit;` fails to compile with following error
```
/usr/include/cip/cipqos.h:32:12: error: declaration does not declare anything [-fpermissive]
32 |   CipUsint explicit; /**< Attr. #8: DSCP value for CIP explicit messages (transport class 2/3 and UCMM)
|            ^~~~~~~~
```
When using OpENer as a library, separate sample configuration link fails with 
```
ld: /usr/lib/../lib/libCIP.a(cipidentity.c.o):(.data.rel.local+0x0): multiple definition of `g_identity'; CMakeFiles/cube-cip.dir/src/CIPApplication.cpp.o:/usr/include/cip/cipidentity.h:74: first defined here
| collect2: error: ld returned 1 exit status
```
Signed-off-by: Vincent Prince <vincent.prince.fr@gmail.com>
> Fix yocto build

- source/src/ports/MINGW/sample_application/sampleapplication.c
The input and output size were changed to 32, and the output assembly number was modified to 151 to match the opener_sample_app.eds file.
> Update sample_application to work with example eds file

- source/src/enet_encap/encap.c
Fragmented packets case a negative number to be
returned by the CreateEncapsulationStructure
function. This change handles this negative number to
be changed to 0 for the remaining byte to be processed
and returns with kEipStatusError.
This change was performed in response to Talos security
report TALOS-2021-1234 and fixes this attack.
> Handles fragmented packet case

- source/src/cip/cipconnectionmanager.c
Increase the condition reporting on open connection failures from
informative to warn. Also include the extended status in the warning
for easier triage on what caused the connection failure in the first
place.
This PR is motivated due to numerous times messing up the connection by mismatching assembly parameters like size or number. The informative level is verbose and not appropriate to enable in production setup. The warning level is more appropriate for this relatively rare condition.
Related, there should be an option to have the logging level runtime switchable.
> Warn on open connection failures

- source/src/cip/cipidentity.c
- source/src/cip/cipstring.c
- source/src/cip/cipstring.h
- source/src/enet_encap/encap.c
- source/src/opener_api.h
This patch series adds a set of missing APIs when using OpENer as a library.  The build-time (cmake options) are still honored and used as defaults.
Since OpENer stores strings internally as a byte array + length, not as C strings with a terminating ASCII `NUL`, a helper API for the `CipShortString` has been included as well, named `GetCstrFromCipShortString()`.
New APIs to manage the CIP Identity Object:
- `SetDeviceRevision()`
- `SetDeviceType()`
- `SetDeviceProductCode()`
- `SetDeviceVendorId()`
- `GetDeviceVendorId()`
- `SetDeviceProductName()`
- `GetDeviceProductName()`
Additionally, an old (unused) macro called `ENCAP_MAX_DELAYED_ENCAP_MESSAGE_SIZE` has been dropped since it referenced the cmake default `OPENER_DEVICE_NAME`.
> New APIs for setting Identity object attributes at runtime

- source/src/cip/cipioconnection.c
- source/src/opener_api.h
This change adds APIs for set and query if the OpENer behavior wrt.  the Run/Idle header on both received and sent CIP cyclic data.  In effect, this makes it possible to build your adapter once and support different types of scanners.  Enabling use of Open Source scanners like [EIPScanner](https://github.com/nimbuscontrols/EIPScanner) for testing your adapter before deploying at a customer site which may require a different behavior.
Previously these were a compile-time options, which is still honored by setting the defaults based on these cmake options.
> APIs for setting Run/Idle header on O->T and T->O frames

- source/src/cip/cipconnectionmanager.c
- source/src/cip/cipconnectionobject.c
- source/src/cip/cipconnectionobject.h
Accept the first consumed sequence number without comparing it to 0.
ODVA CT18.1 will send sequence numbers that starts at 0x80000000, which
will not pass SEQ_GT32 when compared to 0.
This commit adds a boolean flag to the cip_connection_object that
indicates if the eip_level_sequence_count_consuming counter was
initialized with data from the client.
Signed-off-by: Charles Perry <charles.perry@savoirfairelinux.com>
> cip: accept the first consumed sequence number unconditionally

- source/src/ports/MINGW/main.c
- source/src/ports/POSIX/main.c
- source/src/ports/WIN32/main.c
I got a bit of an odd feedback from my customer; "the connection ids are strangely consecutive ...".  After a bit of testing to try and understand what they meant, it slowly dawned on me that they meant between reboots.  
Sure enough, with their report next to me listing the connection ids they had from our adapter in production, I ran the same adapter version on my PC just to notice the exact same upper 16 bits of the connection id .. 0x4567!
Like many others, I suspect, we've built our adapter using the sample application.  So I thought it might be a good idea to share my "fix".  I've only tested it on Linux with GLIBC's `rand()` implementation, and calling `srand()` with the output from `time()` helps a lot.
Mingw should work the same as POSIX, and after a bit of googling it seems …
> Seed PRNG before calling rand()

- source/src/cip/appcontype.c
This is a refactor of GetInputOnlyConnection() and GetListenOnlyConnection()
to support multiple input-only and listen-only connections.  E.g., when
setting up heartbeat (here assembly 254) connections in both directions:
ConfigureInputOnlyConnectionPoint(0, 101, 254, 1);
ConfigureInputOnlyConnectionPoint(1, 254, 100, 1);
Also, increase the default number of supported connections for both input-only
and listen-only for all supported ports.
Signed-off-by: Joachim Wiberg <troglobit@gmail.com>
> Fix #348: support multiple input-only and listen-only connections

- source/CMakeLists.txt
- source/src/cip/cipconnectionmanager.c
- source/src/utils/xorshiftrandom.c
As mentioned in PR #392, some conformance tests may fail an adapter that uses semi-sequential connection IDs.  This patch adds optional support for enabling fully random IDs, where the upper 16-bits are still taken from the per-session incarnation ID and the lower 16-bits are now random from the xor-shift implementation.
Included is an initial seeding using `time(NULL)` if the `SetXorShiftSeed()` function has not been called by the application.
> Add support for random connection IDs also for lower 16-bits

- source/src/cip/cipioconnection.c
- source/src/ports/generic_networkhandler.c
This RFC change set is an attempt at fixing issues described in #393. 
Each respective patch fixes a single problem at a time.  The introduction of the factored-out helper function `transfer_master_connection()` is the only really hairy piece of code, and the one mandating the RFC status of this change set.
Some other minor fixes, and code cleanups for readability, are included as well.
> [RFC PATCH]: Transfer CIP I/O connections on both timeout and close

- source/src/cip/cipioconnection.c
OpenProducingMulticastConnection can possibly be called with a
common_packet_format_data structure that contains both address_info_item
with a non-zero type_id. When this happens, a reasonable alternative
would be to pick the address_info_item that has a type_id already set
the desired final value. Currently, OpenProducingMulticastConnection
will default to the first address_info_item, regardless of its content.
This commit factors out this scheme present in
OpenProducingMulticastConnection and OpenConsumingPointToPointConnection
and puts it in a separate AllocateSocketAddressInfoItem helper function.
Signed-off-by: Charles Perry <charles.perry@savoirfairelinux.com>
> cipioconnection: add the AllocateSocketAddressInfoItem function

- source/src/opener_api.h
[Sonar] Fixes implicit return type conversion for connection_receive_data_function
Signed-off-by: Martin Melik-Merkumians <melik-merkumians@acin.tuwien.ac.at>
> Fix return type conversion

- source/src/ports/WIN32/sample_application/sampleapplication.c
Please test this on a x64 Windows platform. I currently only have 32-bit Windows hosts, which do not generate warnings about these parameters, likely because unsigned is the same size as size_t. This should resolve warnings on 64-bit systems.
> Fix calloc parameter types

- source/src/ports/POSIX/CMakeLists.txt
While adding OpENer support into OpenEmbedded the following error is seen on the installation phase:
| ninja: error: unknown target 'install'
Fix it by adding a install target so that the OpENer binary can be properly installed.
> POSIX: Add a install target entry

- source/src/cip/cipepath.c
- source/src/cip/cipepath.h
As this method leads to compile issues for now I commented it.
> Commented not fully implemented CipEpathEncodeConnectionEpath
